const mongoose = require("mongoose");

const generalDetailsSchema = new mongoose.Schema({
  title: String,
  name: String,
  dateOfJoin: String,
  dateOfBirth: String,
  religion: String,
  staffId: String,
  gender: String,
  employeeId: String,
  bloodGroup: String,
  caste: String,
  department: String,
  designation: String,
  contractType: String,
  category: String,
  institutionLastWorked: String,
  ktuId: String,
  penNo: String,
  maritalStatus: String,
  motherName: String,
  fatherName: String,
  spouseName: String,
  nationality: String,
  houseName: String,
  street: String,
  post2: String,
  district: String,
  pin: String,
  state: String,
  phone: String,
  phoneRes: String,
  email: String,
  officeAddress: String,
  bankName: String,
  accountNo: String,
  bankBranch: String,
  ifsc: String,
  username: String,
  password: String,
}, { timestamps: true });

module.exports = mongoose.model("GeneralDetails", generalDetailsSchema);
